### ISSUE TITLE
New command: dump "partial" mapblocks

### ISSUE THREAD

**Issue by Fixer-007** [Uberi/Minetest-WorldEdit#126]
Say I have a map saved by local map saving hack-feature, since it saves not on mapblock basis, it adds problems.

Now comes "dump partial mapblocks" command, what it does is gradually parses the map for uncomplete mapblocks and just removes them.

Doable?

**Comment by sfan5** [comment]
> since it saves not on mapblock basis,

but it does

What problems does it cause? And generally Lua can't do work on the "raw" MapBlocks.

**Comment by Fixer-007** [comment]
Someone said local_map_saving is not working on mapblock basis but saves differently, so you end up with hacky kind of map save that can crash minetest if you try to set it up as v7 instead of singlenode to have a save you can play further.

**Comment by sfan5** [comment]
@Fixer-007 
I don't know who this someone is, but I can tell you:
I coded `local_map_saving` and it definitely does save on a MapBlock basis.

What it **doesn't** do (because it can't) is saving on a MapChunk basis which can cause problems with some mapgens. However this is a quite rare usecase and shouldn't be in WorldEdit IMO
