### ISSUE TITLE
missing depedince worldedit in worldedit bug

### ISSUE THREAD

**Issue by minetestuser122** [Uberi/Minetest-WorldEdit#174]
i keep trying to run worldedit with and without other mods but keep getting
ERROR[Main]:mod "worldedit_brush" has unsatisfied dependencies:"worldedit_commands" "worldedit"
ERROR[Main]:mod "worldedit_gui" has unsatisfied dependencies:"worldedit_commands" "worldedit"
ERROR[Main]:mod "worldedit_shortcommands" has unsatisfied dependencies:"worldedit_commands"
so its erroring itself

**Comment by sfan5** [comment]
Make sure you have correctly and fully installed <b>and enabled</b> WorldEdit.

**Comment by nawordar** [comment]
I'm sorry, I shouldn't have typed that. Your response wasn't rude at all, but my was. I was a bit frustrated as that was the first page I've found related to my problem and the issue was immediately closed. Yes, OP didn't provide enough info about the problem and it isn't even bug in WorldEdit, but in Minetest (https://github.com/minetest/minetest/issues/4183).

You're doing a great work for Minetest and I'm really thankful for that.
