### ISSUE TITLE
Use chat command return values

### ISSUE THREAD

**Issue by ShadowNinja** [Uberi/Minetest-WorldEdit#60]
Currently `worldedit.player_notify` is used, but all that does now is prepend "WorldEdit -!- ", which is obvious given the context of the command.

**Comment by ShadowNinja** [comment]
@sfan5: This doesn't seem to be fixed...

**Comment by sfan5** [comment]
oh yea indeed, only the cuboid commands do this

**Comment by HybridDog** [comment]
I've implemented it partially: https://github.com/HybridDog/WorldEdit-pack/commit/1807f19501ca49633ac616d66dd80bc8225b22d2
I've also colourized the messages.
It's unfinished: the GUI, brush, and maybe more need to be changed because currently they directly call the function and ignore the return values.

**Comment by HybridDog** [comment]
I've changed the code to use chatcommand return values: #193
I've also colourized the messages and made the GUI code a bit more modular.

**Comment by sfan5** [comment]
Obsoleted by 1d8d9a704fc91e86a7a5204208342bbb48f6e386. Now `worldedit.player_notify` has an actual purpose. Also most WE commands have been converted to use this return style.
